spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/IoTea_dev?useUnicode=true
    username: IoTeaApp
    password: SK*2yWJ46N*WVxSY2%gaAySvYcRM!m$f

debug: true
logging:
  level:
    hu.zza.iotea: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /a
      exposure:
        include: '*'

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/IoTea?useUnicode=true
    username: IoTeaApp
    password: SK*2yWJ46N*WVxSY2%gaAySvYcRM!m$f
  flyway:
    cleanDisabled: true

---

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    connectRetries: 15
    connectRetriesInterval: 60

server:
  error:
    include-message: always

springdoc:
  swagger-ui:
    url: /IoTea_OpenAPI.yaml