spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://localhost:3306/bulbman_test?useUnicode=true
    username: bulbmanApp
    password: s@n2Xt98XsxqjZj%io9wV^6p&vpkGgSe


debug: true
logging:
  level:
    hu.zza.bulbman: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /a
      exposure:
        include: '*'

---

spring:
  config:
    activate:
      on-profile: prod

---

spring:
  profiles:
    active: test

server:
  error:
    include-message: always

springdoc:
  swagger-ui:
    url: /Bulbman_OpenAPI.yaml