openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/{id}:
    get:
      tags:
        - device-controller
      operationId: getDeviceById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Device'
    put:
      tags:
        - device-controller
      operationId: postDevice
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Device'
  /api/:
    get:
      tags:
        - device-controller
      operationId: getAllDevices
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/DeviceAddress'
    DeviceAddress:
      type: object
      properties:
        ip:
          type: object
          properties:
            canonicalHostName:
              type: string
            hostAddress:
              type: string
            address:
              type: array
              items:
                type: string
                format: byte
            hostName:
              type: string
            linkLocalAddress:
              type: boolean
            multicastAddress:
              type: boolean
            anyLocalAddress:
              type: boolean
            loopbackAddress:
              type: boolean
            siteLocalAddress:
              type: boolean
            mcglobal:
              type: boolean
            mcnodeLocal:
              type: boolean
            mclinkLocal:
              type: boolean
            mcsiteLocal:
              type: boolean
            mcorgLocal:
              type: boolean
        reachable:
          type: boolean