CREATE TABLE device_types (
	id BIGINT AUTO_INCREMENT NOT NULL,
	brand VARCHAR(255) NULL,
	model VARCHAR(255) NULL,
	version VARCHAR(255) NULL,
	CONSTRAINT pk_device_types PRIMARY KEY (id)
);

ALTER TABLE devices ADD COLUMN type_id BIGINT NOT NULL;
ALTER TABLE devices ADD CONSTRAINT FK_DEVICES_ON_TYPE FOREIGN KEY (type_id) REFERENCES device_types (id);